config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do 
    resources :pins 
  end 
  
  resources :pins
  root to: "pins#index"


  resources :categories

  resources :pins do
    resources :comments
    member do
      put 'like', to: 'pins#upvote'
    end
  end

    get 'pins/:id/pin_data', to: 'pins#pin_data'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pins 
  has_many :users, through: :pins 

  validates :name, length: {minimum: 2}
  validates :name, uniqueness: true 

  def self.options 
    self.all.map{ |c| [c.name, c.id] }
  end 

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :pin 

	def self.to_time(time) 
		return time.to_formatted_s(:short) 
	end 

end 

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user 
  belongs_to :category
  has_many :comments
  acts_as_votable

  validates :title, length: { minimum: 5 }
  validates :title, presence: true 
  validates :description, presence: true 
  validates :link, :format => URI::regexp(%w(http https)), :allow_blank => true

  has_attached_file :image, :styles => { :medium => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, presence: true 

  def category_attributes=(category)
    self.category = Category.find_or_create_by(name: category["name"])
    self.category.update(category)
  end

  def self.total(user)
    user.pins.length
  end 
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :users
  has_many :pins 
  has_many :categories, through: :pins 

  validates :email, uniqueness: true, on: :create

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable, :omniauth_providers => [:facebook]


    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end

  def self.username(email)
    email.split('@')[0]
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  serialization_scope :view_context


  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end

  
end

app/controllers/categories_controller.rb
require 'pry'
class CategoriesController < ApplicationController
  def index 
    @cateogories = Category.all
  end 

  def show 
    @category = Category.find_by(id: params[:id])
    @categories = Category.all
    @pins = @category.pins 
  end 
  
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	 before_action :authenticate_user!, except: [:index, :show]
   before_action :set_pin 

def new
  @user = current_user 
  @comment = Comment.new 
  respond_to do |format| 
  	format.html #new.html.erb
    format.json { render json: @comment}
  end  
end 

def create
  @comment = Comment.create(:title => params[:comment][:title], :content => params[:comment][:content], :pin_id => params[:pin_id], :username => User.username(current_user.email))
  @comment.created_at = @comment.created_at.to_formatted_s(:short)
  @comment.pin_id = params[:pin_id]
  render json: @comment, status: 201  
end 

private 
  def comment_params
  	params.require(:comment).permit(:content, :title, :id, :username, :pin_id)
  end 

  def set_pin 
    @pin = Pin.find(params[:pin_id])
  end 
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :set_categories, only: [:edit, :new, :create, :update]
  # GET /pins
  # GET /pins.json  
  def index
    @pins = Pin.all
    @categories = Category.all
  end

  # GET /pins/1
  def show
    @pin = Pin.find(params[:id])
    @comment = Comment.new # nested resource  
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @pin}
      end    
  end

  # GET /pins/new
  def new
    @user = current_user
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
    @user = User.find_by(id: params[:id])
  end

  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    respond_to do |format|
      if @pin.valid?
        if !@pin.category[:name].blank?
          @pin.category_id = @pin.category.id 
        else 
          @pin.category_id = params[:category].to_i
        end 
      
        @pin.user_id = current_user.id
        @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        @pin.category_id = @pin.category.id unless @pin.category.id == nil 
        @pin.category_id = params[:category].to_i if @pin.category.id == nil
        @pin.save 

        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def upvote
    @pin.upvote_by(current_user)
    redirect_to :back
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def set_categories 
      @category_options = Category.options 
    end 
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :image, :category, :link, category_attributes: [:name])
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @total = current_user.pins.total(current_user)
    @username = User.username(current_user.email) 
  end 

  private 
  def user_params 
  	params.require(:user).permit(:id)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/categories/_categories.html.erb
<%= select_tag "category", options_for_select(@category_options, @pin.id) %> 

app/views/categories/_list_categories.html.erb
<% categories.each do |c| %> 
  | <%= link_to "#{c.name}", c %> |
<% end %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<section class="clearfix">
		<div class="container">
			<div class="section-left">
				<h1 class="section-title"><%=@category.name%></h1>
        <h5> 
          <%= render partial: 'list_categories', locals: {categories: @categories} %>
        </h5>
			</div>
		</div>
	</section>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <%= render partial: 'pins/all_pins', locals: {pins: @pins} %>

</table>

<br>

app/views/comments/_comments.html.erb
<% @pin.comments.each do |comment| %>
	<h5><%= comment.username %></h5>
	<p><%= comment.content %> <p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@pin, @comment])   do |f| %>
	<div class='field'>
		<h5><%= f.label "Leave a comment here" %></h5>
			<%= f.text_area :content %> 
	</div>

	<div class='action field'>
		<input type="submit" value="Add Comment" />
	</div>
<% end %> 

app/views/comments/create.js.erb
$('#messages-div ul.media-list').append('<li class="media"><%= j @message.body %></li>');

app/views/comments/new.html.erb
<%= render 'form', locals: {user: current_user} %>

app/views/layouts/_header.html.erb
<header class="clearfix">
    <div class="container">
			<div class="header-left">
				<h1>Pinterest-like Clone</h1>
			</div>
			<div class="header-right">
				<label for="open">
					<span class="hidden-desktop"></span>
				</label>
				
        <nav>
				  <% if user_signed_in? %>
            <h5>  
              <%= link_to "Home", root_path %> -
              <%= link_to "My Pins", users_path(current_user) %> -
              <%= link_to 'New Pin', new_user_pin_path(current_user)  %> -
              <%= link_to "Account", edit_user_registration_path  %> -
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> 
            </h5>
            <h6>Signed in as: <%= User.username(current_user.email) %></h6>
          <% else %>
            <h4>  
              <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %> 
              <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %> 
              
            </h4>
          <% end %>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest-like Clone</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/pins/_all_pins.html.erb
<tbody> 
  <div class="transitions-enabled" id="pins">
    <% pins.each do |pin| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag pin.image.url), pin %>
          <h2>
            <%= link_to pin.title, pin %>
          </h2>
      </div>  
    <% end %> 
  </div>
</tbody> 

app/views/pins/_form.html.erb
<%= form_for [current_user, @pin], html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2> 
        <%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved: 
      </h2>

      <ul>
        <% @pin.errors.full_messages.each do |message| %>
          <li> 
            <%= message %> 
          </li>
        <% end %>
      </ul>
    </div> 
  <% end %>

  <div class="field">
    <h5> <%= f.label "Title for your pin" %></h5> 
    <%= f.text_field :title %>
  </div>

  <div class='field'>
    <h5> <%= f.label "Choose an image" %> </h5>
    <%= f.file_field :image %>
  </div>

   <div class="field">
    <h5> <%= f.label "Description"%> </h5>
    <%= f.text_area :description %>
  </div>


  <div class='field'>
    <h5> Create a new category to add your pin to! </h5> 
    
    <%= f.fields_for :category_attributes do |category|%> 
      <%= category.text_field :name %> 
    <% end %> 

    <h4> Or </h4> 
    <h5> Pick a category to add your pin to! </h5>
    <%= render 'categories/categories' %>
  </div>

  <div class="actions field">
    <%= f.submit %>
  </div>

<% end %>

app/views/pins/_logged_in.html.erb
<% if user_signed_in? %>
    <%= link_to like_pin_path(pin), method: :put, class: "btn btn-secondary" do %>
      <span class="glyphicon glyphicon-heart"></span>
      <i class="fa fa-heart"></i>
      <%= pin.get_upvotes.size %>
    <% end %> 
    
    </br></br>

    <% if current_user.pins.include? pin%> 
      <%= link_to "Edit", edit_user_pin_path(current_user), class: "btn btn-default" %>
      <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-secondary" %>
    <% end %> 
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<% if current_user %> 
  <%= render 'form', locals: {pin: @pin, user: current_user} %>
<% end %> 

<%= link_to 'Show', @pin %> | <%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<section class="clearfix">
		<div class="container">
			<div class="section-left">
				<h1 class="section-title">All Pins</h1>
        <h5> 
          <%= render partial: 'categories/list_categories', locals: {categories: @categories} %>
        </h5>
			</div>
		</div>
	</section>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
    <%= render partial: 'all_pins', locals: {pins: @pins} %>
</table>

<br>

app/views/pins/new.html.erb
<%= render 'form', locals: {pin: @pin, user: current_user} %>
<button> <%= link_to 'Back', pins_path %> </button>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>
<div id="show">
   <% if user_signed_in? %>
      <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-secondary" do %>
        <span class="glyphicon glyphicon-heart"></span>
        <i class="fa fa-heart"></i>
        <%= @pin.get_upvotes.size %>
      <% end %> 
       
      </br></br>
       
     
    <a href="#" style="font-size: 12px;" class="js-previous" data-id="<%=@pin.id%>">Previous Pin</a>

    <a href="#" style="padding-left: 520px; font-size: 12px;" class="js-next" data-id="<%=@pin.id%>">Next Pin</a><br><br>
      

    <% if current_user.pins.include? @pin%> 
      <%= link_to "Edit", edit_user_pin_path(current_user), class: "btn btn-default" %>
      <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-secondary" %>
    <% end %> 
  <% end %>
  
  <div id="title">
    <p class="new-title"> <%= @pin.title %> </p>
  </div>
  
  <div id="descrip">
    <p class="new-descrip"> <%= @pin.description %> </p>
  </div>

<br><br><br>

<div class= "form container">
  <% if !current_user.nil? && current_user.pins.exclude?(@pin) %>
    <%= render partial: 'comments/form', locals: {pin: @pin} %>
    <% end %>
  <center>
  </div>


<br><br><br><br><br><br><br><br>

<ul class="append-comments" id="comments">
  <center><button class="js-more" data-id="<%= @pin.id %>">Load comments</button></center>
</ul>

<br><br><br><br><br>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $("#new_comment").on("submit", function(event) {
      event.preventDefault();
      var values = $(this).serialize();
      createComment(values, this)
    })

    function createComment(values, element) {
      var content = $('#comment_content')[0].value;
      if (content !== "") {
        $('#new_comment input:submit').prop('disabled',true);
        $.ajax({
          url: element.action,
          data: values,
          method: 'POST',
          success: function(data) {
            const { content, username } = data;
            let newComment = new Comment(content, username)
            let commentHTML = newComment.formatComment()
            $('#comments').prepend(commentHTML)
            $('#new_comment input:submit').prop('disabled',false);
            element.reset();
          }
        })
      }
    }

    Comment.prototype.formatComment = function() {
      return `<h5> ${this.username} </h5> <center> <p> ${this.content} </p> </center><hr>`
    }

    function Comment(content, username) {
      this.content = content
      this.username = username 
    }

    function toHTML(comment) {
      return `<h5> ${comment.username} </h5> <center> <p> ${comment.content} </p> </center><hr>ajax
      `
    }
  })
</script>


<script type="text/javascript" charset="utf-8">
    $(function() {
      $(".js-more").on("click", function() {
        $('.js-more').hide();
        var id = $(this).data("id");
        $.get("/pins/" + id + ".json", function(data) {
            let comments = data["comments"];
            let cHTML = ``
            comments.forEach(function(comment) {
              cHTML += toHTML(comment)
            })
            $('#comments').prepend(cHTML)
        });
  });
});

</script>

<script type="text/javascript" charset="utf-8">
  var id = parseInt($(".js-next").attr("data-id"))
  
  $(function () {
    $(".js-next").on("click", function() {
      event.preventDefault();
      var nextId = id + 1;
      id = nextId;
      console.log(nextId);
      $.get("/pins/" + nextId + ".json", function(data) {
        var pin = data;
        //$(".new-image").html("<img src=" + pin["image"] +" />");
        $(".new-title").text(pin["title"]);
        $(".new-descrip").text(pin["description"]);
        // re-set the id to current on the link
        let comments = pin["comments"];
        let cHTML = ``
        comments.forEach(function(comment) {
                cHTML += toHTML(comment)
        })
        $('#comments').empty();
        $('#comments').prepend(cHTML)
        $('.image').empty();
        $('.image').val(pin.image)
        $(".js-next").attr("data-id", pin["id"]);
        $(".js-more").attr("data-id", pin["id"]);

      });
    });
  });

  $(function () {
    $(".js-previous").on("click", function() {
      event.preventDefault();
       console.log(parseInt($(".js-previous").attr("data-id")));
      if (parseInt($(".js-previous").attr("data-id")) > 0) {
      var nextId = id - 1;
      id = nextId;
     
    }
      $.get("/pins/" + nextId + ".json", function(data) {
        var pin = data;
        var size = "width: 200px;";
        $(".new-title").text(pin["title"]);
        $(".new-descrip").text(pin["description"]);
        // re-set the id to current on the link
        let comments = pin["comments"];
        let cHTML = ``
        comments.forEach(function(comment) {
                cHTML += toHTML(comment)
        })


        $('#comments').empty();
        $('#comments').prepend(cHTML)
        $('.image').empty();
        $('.image').val(pin.image)
        $(".js-previous").attr("data-id", pin["id"]);
        $(".js-more").attr("data-id", pin["id"]);

      });
    });
  });
</script>

app/views/users/_users_pins.html.erb
 <tbody>
  <div class="transitions-enabled" id="pins">
    <% current_user.pins.each do |pin| %> 
      <div class="box panel panel-default">
        <%= link_to (image_tag pin.image.url), pin %>
        <h2>
          <%= link_to pin.title, pin %>
        </h2>
      </div>  
    <% end %> 
  </div>
</tbody>  

app/views/users/index.html.erb
 <% if user_signed_in? %>
 <h4><%= "#{@username}"%> 's total # of pins: <%= "#{@total}" %> </h4> 
 <% end %>

<div id="the_pins"> <%= render partial: 'users_pins' %>   </div>